with-expecter: true
dir: "test/mocks"
outpkg: mocks
filename: "{{.InterfaceName}}_mock.go"
all: true
packages:
  github.com/iamsr/virallens/backend/internal/domain:
    interfaces:
      UserRepository:
      ConversationRepository:
      GroupRepository:
      MessageRepository:
      RefreshTokenRepository:
      AuthService:
      ConversationService:
      GroupService:
      MessageService:
      JWTService:
