// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/yourusername/virallens/backend/internal/config"
	"github.com/yourusername/virallens/backend/internal/db"
	"github.com/yourusername/virallens/backend/modules/auth"
	"github.com/yourusername/virallens/backend/modules/chat"
	"github.com/yourusername/virallens/backend/modules/user"
	"github.com/yourusername/virallens/backend/modules/websocket"
	"github.com/yourusername/virallens/backend/routes"
)

// Injectors from wire.go:

// InitializeServer sets up the Gin server with all dependencies injected.
func InitializeServer(cfg *config.Config) (*gin.Engine, error) {
	gormDB, err := db.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	repository := user.NewRepository(gormDB)
	refreshTokenRepository := auth.NewRefreshTokenRepository(gormDB)
	jwtService := ProvideJWTService(cfg)
	service := auth.NewService(repository, refreshTokenRepository, jwtService)
	controller := auth.NewController(service)
	userService := user.NewService(repository)
	userController := user.NewController(userService)
	conversationRepository := chat.NewConversationRepository(gormDB)
	conversationService := chat.NewConversationService(conversationRepository, repository)
	messageRepository := chat.NewMessageRepository(gormDB)
	groupRepository := chat.NewGroupRepository(gormDB)
	messageService := chat.NewMessageService(messageRepository, conversationRepository, groupRepository, repository)
	conversationController := chat.NewConversationController(conversationService, messageService)
	groupService := chat.NewGroupService(groupRepository, repository)
	groupController := chat.NewGroupController(groupService, messageService)
	hub := websocket.NewHub()
	handler := websocket.NewHandler(hub, messageService, conversationService, groupService, jwtService)
	engine := routes.SetupRouter(controller, userController, conversationController, groupController, handler, jwtService)
	return engine, nil
}
