// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/yourusername/virallens/backend/internal/api"
	"github.com/yourusername/virallens/backend/internal/config"
	"github.com/yourusername/virallens/backend/internal/middleware"
	"github.com/yourusername/virallens/backend/internal/repository"
	"github.com/yourusername/virallens/backend/internal/service"
	"github.com/yourusername/virallens/backend/internal/websocket"
)

// Injectors from wire.go:

// InitializeApplication wires up all dependencies
func InitializeApplication(cfg *config.Config) (*Application, error) {
	db, err := ProvideDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	refreshTokenRepository := repository.NewRefreshTokenRepository(db)
	jwtService := ProvideJWTService(cfg)
	authService := service.NewAuthService(userRepository, refreshTokenRepository, jwtService)
	authController := api.NewAuthController(authService)
	conversationRepository := repository.NewConversationRepository(db)
	conversationService := service.NewConversationService(conversationRepository, userRepository)
	messageRepository := repository.NewMessageRepository(db)
	groupRepository := repository.NewGroupRepository(db)
	messageService := ProvideMessageService(messageRepository, conversationRepository, userRepository, groupRepository)
	conversationController := api.NewConversationController(conversationService, messageService)
	groupService := service.NewGroupService(groupRepository, userRepository)
	groupController := api.NewGroupController(groupService, messageService)
	jwtMiddleware := ProvideJWTMiddleware(jwtService)
	hub := ProvideWebSocketHub()
	handler := websocket.NewHandler(hub, messageService, conversationService, groupService, jwtService)
	application := &Application{
		Config:                 cfg,
		DB:                     db,
		AuthController:         authController,
		ConversationController: conversationController,
		GroupController:        groupController,
		JWTMiddleware:          jwtMiddleware,
		WebSocketHub:           hub,
		WebSocketHandler:       handler,
	}
	return application, nil
}

// wire.go:

// Application holds all initialized components
type Application struct {
	Config                 *config.Config
	DB                     *sql.DB
	AuthController         *api.AuthController
	ConversationController *api.ConversationController
	GroupController        *api.GroupController
	JWTMiddleware          *middleware.JWTMiddleware
	WebSocketHub           *websocket.Hub
	WebSocketHandler       *websocket.Handler
}
