// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/yourusername/virallens/backend/internal/domain"

	uuid "github.com/google/uuid"
)

// MockConversationRepository is an autogenerated mock type for the ConversationRepository type
type MockConversationRepository struct {
	mock.Mock
}

type MockConversationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationRepository) EXPECT() *MockConversationRepository_Expecter {
	return &MockConversationRepository_Expecter{mock: &_m.Mock}
}

// AddParticipant provides a mock function with given fields: conversationID, userID
func (_m *MockConversationRepository) AddParticipant(conversationID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(conversationID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(conversationID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_AddParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipant'
type MockConversationRepository_AddParticipant_Call struct {
	*mock.Call
}

// AddParticipant is a helper method to define mock.On call
//   - conversationID uuid.UUID
//   - userID uuid.UUID
func (_e *MockConversationRepository_Expecter) AddParticipant(conversationID interface{}, userID interface{}) *MockConversationRepository_AddParticipant_Call {
	return &MockConversationRepository_AddParticipant_Call{Call: _e.mock.On("AddParticipant", conversationID, userID)}
}

func (_c *MockConversationRepository_AddParticipant_Call) Run(run func(conversationID uuid.UUID, userID uuid.UUID)) *MockConversationRepository_AddParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConversationRepository_AddParticipant_Call) Return(_a0 error) *MockConversationRepository_AddParticipant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_AddParticipant_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) error) *MockConversationRepository_AddParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: conversation
func (_m *MockConversationRepository) Create(conversation *domain.Conversation) error {
	ret := _m.Called(conversation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Conversation) error); ok {
		r0 = rf(conversation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockConversationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - conversation *domain.Conversation
func (_e *MockConversationRepository_Expecter) Create(conversation interface{}) *MockConversationRepository_Create_Call {
	return &MockConversationRepository_Create_Call{Call: _e.mock.On("Create", conversation)}
}

func (_c *MockConversationRepository_Create_Call) Run(run func(conversation *domain.Conversation)) *MockConversationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Conversation))
	})
	return _c
}

func (_c *MockConversationRepository_Create_Call) Return(_a0 error) *MockConversationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_Create_Call) RunAndReturn(run func(*domain.Conversation) error) *MockConversationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockConversationRepository) GetByID(id uuid.UUID) (*domain.Conversation, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*domain.Conversation, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *domain.Conversation); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConversationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockConversationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockConversationRepository_Expecter) GetByID(id interface{}) *MockConversationRepository_GetByID_Call {
	return &MockConversationRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockConversationRepository_GetByID_Call) Run(run func(id uuid.UUID)) *MockConversationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockConversationRepository_GetByID_Call) Return(_a0 *domain.Conversation, _a1 error) *MockConversationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConversationRepository_GetByID_Call) RunAndReturn(run func(uuid.UUID) (*domain.Conversation, error)) *MockConversationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByParticipants provides a mock function with given fields: userID1, userID2
func (_m *MockConversationRepository) GetByParticipants(userID1 uuid.UUID, userID2 uuid.UUID) (*domain.Conversation, error) {
	ret := _m.Called(userID1, userID2)

	if len(ret) == 0 {
		panic("no return value specified for GetByParticipants")
	}

	var r0 *domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*domain.Conversation, error)); ok {
		return rf(userID1, userID2)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *domain.Conversation); ok {
		r0 = rf(userID1, userID2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(userID1, userID2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConversationRepository_GetByParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByParticipants'
type MockConversationRepository_GetByParticipants_Call struct {
	*mock.Call
}

// GetByParticipants is a helper method to define mock.On call
//   - userID1 uuid.UUID
//   - userID2 uuid.UUID
func (_e *MockConversationRepository_Expecter) GetByParticipants(userID1 interface{}, userID2 interface{}) *MockConversationRepository_GetByParticipants_Call {
	return &MockConversationRepository_GetByParticipants_Call{Call: _e.mock.On("GetByParticipants", userID1, userID2)}
}

func (_c *MockConversationRepository_GetByParticipants_Call) Run(run func(userID1 uuid.UUID, userID2 uuid.UUID)) *MockConversationRepository_GetByParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConversationRepository_GetByParticipants_Call) Return(_a0 *domain.Conversation, _a1 error) *MockConversationRepository_GetByParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConversationRepository_GetByParticipants_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (*domain.Conversation, error)) *MockConversationRepository_GetByParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// IsParticipant provides a mock function with given fields: conversationID, userID
func (_m *MockConversationRepository) IsParticipant(conversationID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(conversationID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsParticipant")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(conversationID, userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(conversationID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(conversationID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConversationRepository_IsParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsParticipant'
type MockConversationRepository_IsParticipant_Call struct {
	*mock.Call
}

// IsParticipant is a helper method to define mock.On call
//   - conversationID uuid.UUID
//   - userID uuid.UUID
func (_e *MockConversationRepository_Expecter) IsParticipant(conversationID interface{}, userID interface{}) *MockConversationRepository_IsParticipant_Call {
	return &MockConversationRepository_IsParticipant_Call{Call: _e.mock.On("IsParticipant", conversationID, userID)}
}

func (_c *MockConversationRepository_IsParticipant_Call) Run(run func(conversationID uuid.UUID, userID uuid.UUID)) *MockConversationRepository_IsParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConversationRepository_IsParticipant_Call) Return(_a0 bool, _a1 error) *MockConversationRepository_IsParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConversationRepository_IsParticipant_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (bool, error)) *MockConversationRepository_IsParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: userID
func (_m *MockConversationRepository) ListByUserID(userID uuid.UUID) ([]*domain.Conversation, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]*domain.Conversation, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*domain.Conversation); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConversationRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockConversationRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockConversationRepository_Expecter) ListByUserID(userID interface{}) *MockConversationRepository_ListByUserID_Call {
	return &MockConversationRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", userID)}
}

func (_c *MockConversationRepository_ListByUserID_Call) Run(run func(userID uuid.UUID)) *MockConversationRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockConversationRepository_ListByUserID_Call) Return(_a0 []*domain.Conversation, _a1 error) *MockConversationRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConversationRepository_ListByUserID_Call) RunAndReturn(run func(uuid.UUID) ([]*domain.Conversation, error)) *MockConversationRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConversationRepository creates a new instance of MockConversationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationRepository {
	mock := &MockConversationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
