// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/yourusername/virallens/backend/internal/domain"

	uuid "github.com/google/uuid"
)

// MockGroupRepository is an autogenerated mock type for the GroupRepository type
type MockGroupRepository struct {
	mock.Mock
}

type MockGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupRepository) EXPECT() *MockGroupRepository_Expecter {
	return &MockGroupRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: groupID, userID
func (_m *MockGroupRepository) AddMember(groupID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockGroupRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - groupID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGroupRepository_Expecter) AddMember(groupID interface{}, userID interface{}) *MockGroupRepository_AddMember_Call {
	return &MockGroupRepository_AddMember_Call{Call: _e.mock.On("AddMember", groupID, userID)}
}

func (_c *MockGroupRepository_AddMember_Call) Run(run func(groupID uuid.UUID, userID uuid.UUID)) *MockGroupRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupRepository_AddMember_Call) Return(_a0 error) *MockGroupRepository_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_AddMember_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) error) *MockGroupRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: group
func (_m *MockGroupRepository) Create(group *domain.Group) error {
	ret := _m.Called(group)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Group) error); ok {
		r0 = rf(group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - group *domain.Group
func (_e *MockGroupRepository_Expecter) Create(group interface{}) *MockGroupRepository_Create_Call {
	return &MockGroupRepository_Create_Call{Call: _e.mock.On("Create", group)}
}

func (_c *MockGroupRepository_Create_Call) Run(run func(group *domain.Group)) *MockGroupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Group))
	})
	return _c
}

func (_c *MockGroupRepository_Create_Call) Return(_a0 error) *MockGroupRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_Create_Call) RunAndReturn(run func(*domain.Group) error) *MockGroupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockGroupRepository) GetByID(id uuid.UUID) (*domain.Group, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*domain.Group, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *domain.Group); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGroupRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockGroupRepository_Expecter) GetByID(id interface{}) *MockGroupRepository_GetByID_Call {
	return &MockGroupRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockGroupRepository_GetByID_Call) Run(run func(id uuid.UUID)) *MockGroupRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupRepository_GetByID_Call) Return(_a0 *domain.Group, _a1 error) *MockGroupRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_GetByID_Call) RunAndReturn(run func(uuid.UUID) (*domain.Group, error)) *MockGroupRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// IsMember provides a mock function with given fields: groupID, userID
func (_m *MockGroupRepository) IsMember(groupID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(groupID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_IsMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMember'
type MockGroupRepository_IsMember_Call struct {
	*mock.Call
}

// IsMember is a helper method to define mock.On call
//   - groupID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGroupRepository_Expecter) IsMember(groupID interface{}, userID interface{}) *MockGroupRepository_IsMember_Call {
	return &MockGroupRepository_IsMember_Call{Call: _e.mock.On("IsMember", groupID, userID)}
}

func (_c *MockGroupRepository_IsMember_Call) Run(run func(groupID uuid.UUID, userID uuid.UUID)) *MockGroupRepository_IsMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupRepository_IsMember_Call) Return(_a0 bool, _a1 error) *MockGroupRepository_IsMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_IsMember_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) (bool, error)) *MockGroupRepository_IsMember_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: userID
func (_m *MockGroupRepository) ListByUserID(userID uuid.UUID) ([]*domain.Group, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]*domain.Group, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*domain.Group); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockGroupRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockGroupRepository_Expecter) ListByUserID(userID interface{}) *MockGroupRepository_ListByUserID_Call {
	return &MockGroupRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", userID)}
}

func (_c *MockGroupRepository_ListByUserID_Call) Run(run func(userID uuid.UUID)) *MockGroupRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupRepository_ListByUserID_Call) Return(_a0 []*domain.Group, _a1 error) *MockGroupRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_ListByUserID_Call) RunAndReturn(run func(uuid.UUID) ([]*domain.Group, error)) *MockGroupRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: groupID, userID
func (_m *MockGroupRepository) RemoveMember(groupID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockGroupRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - groupID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGroupRepository_Expecter) RemoveMember(groupID interface{}, userID interface{}) *MockGroupRepository_RemoveMember_Call {
	return &MockGroupRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", groupID, userID)}
}

func (_c *MockGroupRepository_RemoveMember_Call) Run(run func(groupID uuid.UUID, userID uuid.UUID)) *MockGroupRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupRepository_RemoveMember_Call) Return(_a0 error) *MockGroupRepository_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_RemoveMember_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) error) *MockGroupRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupRepository creates a new instance of MockGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupRepository {
	mock := &MockGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
