// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/yourusername/virallens/backend/internal/domain"

	time "time"

	uuid "github.com/google/uuid"
)

// MockMessageRepository is an autogenerated mock type for the MessageRepository type
type MockMessageRepository struct {
	mock.Mock
}

type MockMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepository) EXPECT() *MockMessageRepository_Expecter {
	return &MockMessageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: message
func (_m *MockMessageRepository) Create(message *domain.Message) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Message) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - message *domain.Message
func (_e *MockMessageRepository_Expecter) Create(message interface{}) *MockMessageRepository_Create_Call {
	return &MockMessageRepository_Create_Call{Call: _e.mock.On("Create", message)}
}

func (_c *MockMessageRepository_Create_Call) Run(run func(message *domain.Message)) *MockMessageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Message))
	})
	return _c
}

func (_c *MockMessageRepository_Create_Call) Return(_a0 error) *MockMessageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRepository_Create_Call) RunAndReturn(run func(*domain.Message) error) *MockMessageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockMessageRepository) GetByID(id uuid.UUID) (*domain.Message, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*domain.Message, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *domain.Message); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMessageRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockMessageRepository_Expecter) GetByID(id interface{}) *MockMessageRepository_GetByID_Call {
	return &MockMessageRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockMessageRepository_GetByID_Call) Run(run func(id uuid.UUID)) *MockMessageRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockMessageRepository_GetByID_Call) Return(_a0 *domain.Message, _a1 error) *MockMessageRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepository_GetByID_Call) RunAndReturn(run func(uuid.UUID) (*domain.Message, error)) *MockMessageRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByConversationID provides a mock function with given fields: conversationID, cursor, limit
func (_m *MockMessageRepository) ListByConversationID(conversationID uuid.UUID, cursor *time.Time, limit int) ([]*domain.Message, error) {
	ret := _m.Called(conversationID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByConversationID")
	}

	var r0 []*domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *time.Time, int) ([]*domain.Message, error)); ok {
		return rf(conversationID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, *time.Time, int) []*domain.Message); ok {
		r0 = rf(conversationID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, *time.Time, int) error); ok {
		r1 = rf(conversationID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepository_ListByConversationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByConversationID'
type MockMessageRepository_ListByConversationID_Call struct {
	*mock.Call
}

// ListByConversationID is a helper method to define mock.On call
//   - conversationID uuid.UUID
//   - cursor *time.Time
//   - limit int
func (_e *MockMessageRepository_Expecter) ListByConversationID(conversationID interface{}, cursor interface{}, limit interface{}) *MockMessageRepository_ListByConversationID_Call {
	return &MockMessageRepository_ListByConversationID_Call{Call: _e.mock.On("ListByConversationID", conversationID, cursor, limit)}
}

func (_c *MockMessageRepository_ListByConversationID_Call) Run(run func(conversationID uuid.UUID, cursor *time.Time, limit int)) *MockMessageRepository_ListByConversationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(*time.Time), args[2].(int))
	})
	return _c
}

func (_c *MockMessageRepository_ListByConversationID_Call) Return(_a0 []*domain.Message, _a1 error) *MockMessageRepository_ListByConversationID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepository_ListByConversationID_Call) RunAndReturn(run func(uuid.UUID, *time.Time, int) ([]*domain.Message, error)) *MockMessageRepository_ListByConversationID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByGroupID provides a mock function with given fields: groupID, cursor, limit
func (_m *MockMessageRepository) ListByGroupID(groupID uuid.UUID, cursor *time.Time, limit int) ([]*domain.Message, error) {
	ret := _m.Called(groupID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByGroupID")
	}

	var r0 []*domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *time.Time, int) ([]*domain.Message, error)); ok {
		return rf(groupID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, *time.Time, int) []*domain.Message); ok {
		r0 = rf(groupID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, *time.Time, int) error); ok {
		r1 = rf(groupID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepository_ListByGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByGroupID'
type MockMessageRepository_ListByGroupID_Call struct {
	*mock.Call
}

// ListByGroupID is a helper method to define mock.On call
//   - groupID uuid.UUID
//   - cursor *time.Time
//   - limit int
func (_e *MockMessageRepository_Expecter) ListByGroupID(groupID interface{}, cursor interface{}, limit interface{}) *MockMessageRepository_ListByGroupID_Call {
	return &MockMessageRepository_ListByGroupID_Call{Call: _e.mock.On("ListByGroupID", groupID, cursor, limit)}
}

func (_c *MockMessageRepository_ListByGroupID_Call) Run(run func(groupID uuid.UUID, cursor *time.Time, limit int)) *MockMessageRepository_ListByGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(*time.Time), args[2].(int))
	})
	return _c
}

func (_c *MockMessageRepository_ListByGroupID_Call) Return(_a0 []*domain.Message, _a1 error) *MockMessageRepository_ListByGroupID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepository_ListByGroupID_Call) RunAndReturn(run func(uuid.UUID, *time.Time, int) ([]*domain.Message, error)) *MockMessageRepository_ListByGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageRepository creates a new instance of MockMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	mock := &MockMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
