// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/yourusername/virallens/backend/internal/domain"

	uuid "github.com/google/uuid"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: token
func (_m *MockRefreshTokenRepository) Create(token *domain.RefreshToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.RefreshToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - token *domain.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Create(token interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", token)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(token *domain.RefreshToken)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(_a0 error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(*domain.RefreshToken) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: userID
func (_m *MockRefreshTokenRepository) DeleteByUserID(userID uuid.UUID) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockRefreshTokenRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) DeleteByUserID(userID interface{}) *MockRefreshTokenRepository_DeleteByUserID_Call {
	return &MockRefreshTokenRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", userID)}
}

func (_c *MockRefreshTokenRepository_DeleteByUserID_Call) Run(run func(userID uuid.UUID)) *MockRefreshTokenRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByUserID_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByUserID_Call) RunAndReturn(run func(uuid.UUID) error) *MockRefreshTokenRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with no fields
func (_m *MockRefreshTokenRepository) DeleteExpired() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockRefreshTokenRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
func (_e *MockRefreshTokenRepository_Expecter) DeleteExpired() *MockRefreshTokenRepository_DeleteExpired_Call {
	return &MockRefreshTokenRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired")}
}

func (_c *MockRefreshTokenRepository_DeleteExpired_Call) Run(run func()) *MockRefreshTokenRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteExpired_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteExpired_Call) RunAndReturn(run func() error) *MockRefreshTokenRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// GetByToken provides a mock function with given fields: token
func (_m *MockRefreshTokenRepository) GetByToken(token string) (*domain.RefreshToken, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.RefreshToken, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.RefreshToken); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_GetByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByToken'
type MockRefreshTokenRepository_GetByToken_Call struct {
	*mock.Call
}

// GetByToken is a helper method to define mock.On call
//   - token string
func (_e *MockRefreshTokenRepository_Expecter) GetByToken(token interface{}) *MockRefreshTokenRepository_GetByToken_Call {
	return &MockRefreshTokenRepository_GetByToken_Call{Call: _e.mock.On("GetByToken", token)}
}

func (_c *MockRefreshTokenRepository_GetByToken_Call) Run(run func(token string)) *MockRefreshTokenRepository_GetByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_GetByToken_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockRefreshTokenRepository_GetByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_GetByToken_Call) RunAndReturn(run func(string) (*domain.RefreshToken, error)) *MockRefreshTokenRepository_GetByToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
